### ISSUE TITLE
OTA Update failed - ErrNo 104

### ISSUE THREAD

**Issue by irqnet** [sairon/esphome-nspanel-lovelace-ui#15] opened 2022-11-09 09:40 UTC
I've reflashed my NSPanel using the OTA Update from Tasmota, which worked like charm.

I did some small adaptions on the esphome code for the physical button handly and tried to OTA update afterwards, which fails with ErrNo 104 everytime.

`RAM:   [=         ]  12.9% (used 42292 bytes from 327680 bytes)
Flash: [======    ]  62.8% (used 1152788 bytes from 1835008 bytes)
========================= [SUCCESS] Took 17.27 seconds =========================
INFO Successfully compiled program.
INFO Resolving IP address of nspanel_treppe.local
INFO  -> 192.168.60.137
INFO Uploading /data/nspanel_treppe/.pioenvs/nspanel_treppe/firmware.bin (1152896 bytes)
Uploading: [=                                                           ] 1% 
ERROR Error sending data: [Errno 104] Connection reset by peer`

Anyone experienced that either? It seems that I need to reflash it with my USB adapter again, which is really annoying to be honest.

**Comment by sairon** [comment] 2022-11-24 11:10
Hi @irqnet, this doesn't seem to be issue in this component. There is possibly some problem in the device's connectivity or the device itself (the network reset could be caused by power brownout, or a similar problem). I'm closing this issue because there is nothing to be changed in this repository to remedy your situation. For further help or discussion please use official ESPHome Discord or similar channels.

**Closed as completed by sairon** 2022-11-24 11:10 UTC
